name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build
      run: make

    - name: Run clean build test
      run: |
        make clean
        make

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: webserver
        path: build/webserver
