name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build
      run: |
        mkdir -p build
        make

    - name: Run tests
      run: |
        if [ -f Makefile ] && grep -q "^test:" Makefile; then
          make test
        else
          echo "No tests defined"
        fi

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: server-binary
        path: build/
